export type CrowdLevel = 'Low' | 'Medium' | 'High';

export interface Place {
  id: string;
  name: string;
  city: string;
  category: 'Cafe' | 'Park' | 'Historic' | 'Beach' | 'Nature';
  description: string;
  imageUrl: string;
  crowdLevel: CrowdLevel;
  authenticityScore: number;
  rating: number;
  reviews: number;
  lat: number;
  lng: number;
  isTouristFavorite: boolean;
  isHiddenGem: boolean;
}

export const MOCK_PLACES: Place[] = [
  // MUMBAI
  {
    id: 'm1',
    name: 'Kyani & Co.',
    city: 'Mumbai',
    category: 'Cafe',
    description: 'A legendary Irani cafe established in 1904. Famous for its cherry custard, mawa cake, and the timeless atmosphere of old Bombay.',
    imageUrl: 'https://picsum.photos/seed/kyani/600/400',
    crowdLevel: 'High',
    authenticityScore: 96,
    rating: 4.6,
    reviews: 8200,
    lat: 18.9433,
    lng: 72.8258,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'm2',
    name: 'Subko Specialty Coffee',
    city: 'Mumbai',
    category: 'Cafe',
    description: 'Tucked away in a restored bungalow in Bandra, this roastery represents modern Indian coffee culture at its most authentic.',
    imageUrl: 'https://picsum.photos/seed/subko/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 92,
    rating: 4.8,
    reviews: 1200,
    lat: 19.0544,
    lng: 72.8255,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'm3',
    name: 'Banganga Tank',
    city: 'Mumbai',
    category: 'Historic',
    description: 'An ancient water tank surrounded by temples. A remarkably calm spiritual pocket that feels worlds away from the city chaos.',
    imageUrl: 'https://picsum.photos/seed/banganga/600/400',
    crowdLevel: 'Low',
    authenticityScore: 98,
    rating: 4.5,
    reviews: 2100,
    lat: 18.9454,
    lng: 72.7932,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'm4',
    name: 'Marine Drive',
    city: 'Mumbai',
    category: 'Beach',
    description: 'The iconic Queen\'s Necklace. A 3.6km long promenade that is the most famous spot to watch the Mumbai sunset.',
    imageUrl: 'https://picsum.photos/seed/marine/600/400',
    crowdLevel: 'High',
    authenticityScore: 70,
    rating: 4.7,
    reviews: 150000,
    lat: 18.9431,
    lng: 72.8230,
    isTouristFavorite: true,
    isHiddenGem: false,
  },

  // HAMPI
  {
    id: 'h1',
    name: 'Virupaksha Temple',
    city: 'Hampi',
    category: 'Historic',
    description: 'The oldest functional temple in India, a majestic marvel of Vijayanagara architecture and the spiritual heart of the ruins.',
    imageUrl: 'https://picsum.photos/seed/virupaksha/600/400',
    crowdLevel: 'High',
    authenticityScore: 88,
    rating: 4.9,
    reviews: 45000,
    lat: 15.3350,
    lng: 76.4600,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'h2',
    name: 'Sanapur Reservoir',
    city: 'Hampi',
    category: 'Nature',
    description: 'Across the Tungabhadra river, this quiet reservoir offers stunning boulder-strewn landscapes and cliff jumping in deep blue waters.',
    imageUrl: 'https://picsum.photos/seed/sanapur/600/400',
    crowdLevel: 'Low',
    authenticityScore: 94,
    rating: 4.7,
    reviews: 1800,
    lat: 15.3500,
    lng: 76.4400,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'h3',
    name: 'Anegundi Village',
    city: 'Hampi',
    category: 'Historic',
    description: 'Considered the older kingdom than Hampi, this village preserves traditional life and ancient Hanuman temples on Kishkindha hill.',
    imageUrl: 'https://picsum.photos/seed/anegundi/600/400',
    crowdLevel: 'Low',
    authenticityScore: 97,
    rating: 4.6,
    reviews: 950,
    lat: 15.3550,
    lng: 76.4850,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'h4',
    name: 'Hemakuta Hill',
    city: 'Hampi',
    category: 'Historic',
    description: 'A cluster of ancient pre-Vijayanagara temples. The best spot to watch the sunrise over the Hampi ruins without the crowds.',
    imageUrl: 'https://picsum.photos/seed/hemakuta/600/400',
    crowdLevel: 'Low',
    authenticityScore: 99,
    rating: 4.8,
    reviews: 500,
    lat: 15.3330,
    lng: 76.4580,
    isTouristFavorite: false,
    isHiddenGem: true,
  },

  // VARANASI
  {
    id: 'v1',
    name: 'Dashashwamedh Ghat',
    city: 'Varanasi',
    category: 'Historic',
    description: 'The main and most spectacular ghat. Witness the nightly Ganga Aarti, a mesmerizing symphony of fire, incense, and chants.',
    imageUrl: 'https://picsum.photos/seed/dashas/600/400',
    crowdLevel: 'High',
    authenticityScore: 75,
    rating: 4.8,
    reviews: 89000,
    lat: 25.3075,
    lng: 83.0105,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'v2',
    name: 'Munshi Ghat',
    city: 'Varanasi',
    category: 'Historic',
    description: 'A beautifully preserved 19th-century palace ghat. Much quieter than the main ghats, perfect for early morning reflection.',
    imageUrl: 'https://picsum.photos/seed/munshi/600/400',
    crowdLevel: 'Low',
    authenticityScore: 93,
    rating: 4.7,
    reviews: 450,
    lat: 25.3040,
    lng: 83.0080,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'v3',
    name: 'Blue Lassi Shop',
    city: 'Varanasi',
    category: 'Cafe',
    description: 'A tiny, iconic hole-in-the-wall near the burning ghats. Serving dozens of flavors of hand-churned lassi in clay pots for decades.',
    imageUrl: 'https://picsum.photos/seed/bluelassi/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 98,
    rating: 4.9,
    reviews: 3500,
    lat: 25.3110,
    lng: 83.0130,
    isTouristFavorite: false,
    isHiddenGem: true,
  },

  // KOLKATA
  {
    id: 'k1',
    name: "8th Day Café & Bakery",
    city: "Kolkata",
    category: "Cafe",
    lat: 22.5186,
    lng: 88.3654,
    rating: 4.6,
    reviews: 420,
    description: "Popular modern café with great coffee and a lively atmosphere. Often crowded but loved by tourists.",
    imageUrl: "https://images.unsplash.com/photo-1509042239860-f550ce710b93",
    crowdLevel: 'High',
    authenticityScore: 85,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'k2',
    name: "Indian Coffee House, College Street",
    city: "Kolkata",
    category: "Cafe",
    lat: 22.5769,
    lng: 88.3639,
    rating: 4.3,
    reviews: 1200,
    description: "Historic and iconic café, very popular among locals and tourists. Crowded but culturally rich.",
    imageUrl: "https://images.unsplash.com/photo-1521017432531-fbd92d768814",
    crowdLevel: 'High',
    authenticityScore: 95,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'k3',
    name: "Rabindra Sarobar Lake",
    city: "Kolkata",
    category: "Park",
    lat: 22.5129,
    lng: 88.3515,
    rating: 4.5,
    reviews: 300,
    description: "Peaceful lake area ideal for walks and quiet mornings. A local favorite away from heavy crowds.",
    imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    crowdLevel: 'Low',
    authenticityScore: 92,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k4',
    name: "Princep Ghat",
    city: "Kolkata",
    category: "Historic",
    lat: 22.5635,
    lng: 88.3387,
    rating: 4.4,
    reviews: 950,
    description: "Beautiful riverside spot with colonial architecture. Popular and crowded during evenings.",
    imageUrl: "https://images.unsplash.com/photo-1580655653885-65763b2597d0",
    crowdLevel: 'High',
    authenticityScore: 80,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'k5',
    name: "Kumartuli",
    city: "Kolkata",
    category: "Historic",
    lat: 22.6026,
    lng: 88.3624,
    rating: 4.6,
    reviews: 180,
    description: "Hidden artisan district where idols are crafted. Quiet, authentic and deeply local experience.",
    imageUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    crowdLevel: 'Low',
    authenticityScore: 100,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k6',
    name: "Eco Park",
    city: "Kolkata",
    category: "Park",
    lat: 22.5839,
    lng: 88.4667,
    rating: 4.3,
    reviews: 800,
    description: "Large urban park with attractions. Popular tourist spot with moderate to heavy crowd.",
    imageUrl: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee",
    crowdLevel: 'High',
    authenticityScore: 75,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'k7',
    name: "South Park Street Cemetery",
    city: "Kolkata",
    category: "Historic",
    lat: 22.5448,
    lng: 88.3564,
    rating: 4.5,
    reviews: 140,
    description: "Quiet colonial-era cemetery. Peaceful and less crowded, perfect for calm exploration.",
    imageUrl: "https://images.unsplash.com/photo-1526778548025-fa2f459cd5ce",
    crowdLevel: 'Low',
    authenticityScore: 98,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k8',
    name: "Maidan",
    city: "Kolkata",
    category: "Park",
    lat: 22.5600,
    lng: 88.3490,
    rating: 4.4,
    reviews: 500,
    description: "Huge open field in the city. Popular but spacious enough for quiet spots.",
    imageUrl: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    crowdLevel: 'Medium',
    authenticityScore: 90,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k9',
    name: "Flurys, Park Street",
    city: "Kolkata",
    category: "Cafe",
    lat: 22.5510,
    lng: 88.3520,
    rating: 4.5,
    reviews: 1100,
    description: "Iconic bakery with colonial charm. Highly popular and often crowded.",
    imageUrl: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085",
    crowdLevel: 'High',
    authenticityScore: 88,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'k10',
    name: "Jorasanko Thakur Bari",
    city: "Kolkata",
    category: "Historic",
    lat: 22.5855,
    lng: 88.3593,
    rating: 4.6,
    reviews: 200,
    description: "Historic house of Rabindranath Tagore. Calm and culturally rich, not overcrowded.",
    imageUrl: "https://images.unsplash.com/photo-1549880187-7f5a2f6c7f0d",
    crowdLevel: 'Low',
    authenticityScore: 97,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k11',
    name: "Ballygunge Place",
    city: "Kolkata",
    category: "Cafe",
    lat: 22.5230,
    lng: 88.3640,
    rating: 4.6,
    reviews: 250,
    description: "Authentic Bengali cuisine in a calm environment. Loved by locals, not too crowded.",
    imageUrl: "https://images.unsplash.com/photo-1544025162-d76694265947",
    crowdLevel: 'Low',
    authenticityScore: 94,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k12',
    name: "Botanical Garden",
    city: "Kolkata",
    category: "Park",
    lat: 22.5583,
    lng: 88.2872,
    rating: 4.5,
    reviews: 400,
    description: "Serene garden with the Great Banyan Tree. Peaceful and less crowded.",
    imageUrl: "https://images.unsplash.com/photo-1470770841072-f978cf4d019e",
    crowdLevel: 'Low',
    authenticityScore: 96,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'k13',
    name: "New Market",
    city: "Kolkata",
    category: "Historic",
    lat: 22.5606,
    lng: 88.3517,
    rating: 4.3,
    reviews: 1300,
    description: "Busy shopping hub. Extremely crowded but vibrant and popular.",
    imageUrl: "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
    crowdLevel: 'High',
    authenticityScore: 82,
    isTouristFavorite: true,
    isHiddenGem: false,
  }
];
