export type CrowdLevel = 'Low' | 'Medium' | 'High';

export interface Place {
  id: string;
  name: string;
  city: string;
  category: 'Cafe' | 'Park' | 'Historic' | 'Beach' | 'Nature';
  description: string;
  imageUrl: string;
  crowdLevel: CrowdLevel;
  authenticityScore: number;
  rating: number;
  reviews: number;
  lat: number;
  lng: number;
  isTouristFavorite: boolean;
  isHiddenGem: boolean;
}

export const MOCK_PLACES: Place[] = [
  // MUMBAI
  {
    id: 'm1',
    name: 'Kyani & Co.',
    city: 'Mumbai',
    category: 'Cafe',
    description: 'A legendary Irani cafe established in 1904. Famous for its cherry custard, mawa cake, and the timeless atmosphere of old Bombay.',
    imageUrl: 'https://picsum.photos/seed/kyani/600/400',
    crowdLevel: 'High',
    authenticityScore: 96,
    rating: 4.6,
    reviews: 8200,
    lat: 18.9433,
    lng: 72.8258,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'm2',
    name: 'Subko Specialty Coffee',
    city: 'Mumbai',
    category: 'Cafe',
    description: 'Tucked away in a restored bungalow in Bandra, this roastery represents modern Indian coffee culture at its most authentic.',
    imageUrl: 'https://picsum.photos/seed/subko/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 92,
    rating: 4.8,
    reviews: 1200,
    lat: 19.0544,
    lng: 72.8255,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'm3',
    name: 'Banganga Tank',
    city: 'Mumbai',
    category: 'Historic',
    description: 'An ancient water tank surrounded by temples. A remarkably calm spiritual pocket that feels worlds away from the city chaos.',
    imageUrl: 'https://picsum.photos/seed/banganga/600/400',
    crowdLevel: 'Low',
    authenticityScore: 98,
    rating: 4.5,
    reviews: 2100,
    lat: 18.9454,
    lng: 72.7932,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'm4',
    name: 'Marine Drive',
    city: 'Mumbai',
    category: 'Beach',
    description: 'The iconic Queen\'s Necklace. A 3.6km long promenade that is the most famous spot to watch the Mumbai sunset.',
    imageUrl: 'https://picsum.photos/seed/marine/600/400',
    crowdLevel: 'High',
    authenticityScore: 70,
    rating: 4.7,
    reviews: 150000,
    lat: 18.9431,
    lng: 72.8230,
    isTouristFavorite: true,
    isHiddenGem: false,
  },

  // HAMPI
  {
    id: 'h1',
    name: 'Virupaksha Temple',
    city: 'Hampi',
    category: 'Historic',
    description: 'The oldest functional temple in India, a majestic marvel of Vijayanagara architecture and the spiritual heart of the ruins.',
    imageUrl: 'https://picsum.photos/seed/virupaksha/600/400',
    crowdLevel: 'High',
    authenticityScore: 88,
    rating: 4.9,
    reviews: 45000,
    lat: 15.3350,
    lng: 76.4600,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'h2',
    name: 'Sanapur Reservoir',
    city: 'Hampi',
    category: 'Nature',
    description: 'Across the Tungabhadra river, this quiet reservoir offers stunning boulder-strewn landscapes and cliff jumping in deep blue waters.',
    imageUrl: 'https://picsum.photos/seed/sanapur/600/400',
    crowdLevel: 'Low',
    authenticityScore: 94,
    rating: 4.7,
    reviews: 1800,
    lat: 15.3500,
    lng: 76.4400,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'h3',
    name: 'Anegundi Village',
    city: 'Hampi',
    category: 'Historic',
    description: 'Considered the older kingdom than Hampi, this village preserves traditional life and ancient Hanuman temples on Kishkindha hill.',
    imageUrl: 'https://picsum.photos/seed/anegundi/600/400',
    crowdLevel: 'Low',
    authenticityScore: 97,
    rating: 4.6,
    reviews: 950,
    lat: 15.3550,
    lng: 76.4850,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'h4',
    name: 'Hemakuta Hill',
    city: 'Hampi',
    category: 'Historic',
    description: 'A cluster of ancient pre-Vijayanagara temples. The best spot to watch the sunrise over the Hampi ruins without the crowds.',
    imageUrl: 'https://picsum.photos/seed/hemakuta/600/400',
    crowdLevel: 'Low',
    authenticityScore: 99,
    rating: 4.8,
    reviews: 500,
    lat: 15.3330,
    lng: 76.4580,
    isTouristFavorite: false,
    isHiddenGem: true,
  },

  // VARANASI
  {
    id: 'v1',
    name: 'Dashashwamedh Ghat',
    city: 'Varanasi',
    category: 'Historic',
    description: 'The main and most spectacular ghat. Witness the nightly Ganga Aarti, a mesmerizing symphony of fire, incense, and chants.',
    imageUrl: 'https://picsum.photos/seed/dashas/600/400',
    crowdLevel: 'High',
    authenticityScore: 75,
    rating: 4.8,
    reviews: 89000,
    lat: 25.3075,
    lng: 83.0105,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'v2',
    name: 'Munshi Ghat',
    city: 'Varanasi',
    category: 'Historic',
    description: 'A beautifully preserved 19th-century palace ghat. Much quieter than the main ghats, perfect for early morning reflection.',
    imageUrl: 'https://picsum.photos/seed/munshi/600/400',
    crowdLevel: 'Low',
    authenticityScore: 93,
    rating: 4.7,
    reviews: 450,
    lat: 25.3040,
    lng: 83.0080,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'v3',
    name: 'Blue Lassi Shop',
    city: 'Varanasi',
    category: 'Cafe',
    description: 'A tiny, iconic hole-in-the-wall near the burning ghats. Serving dozens of flavors of hand-churned lassi in clay pots for decades.',
    imageUrl: 'https://picsum.photos/seed/bluelassi/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 98,
    rating: 4.9,
    reviews: 3500,
    lat: 25.3110,
    lng: 83.0130,
    isTouristFavorite: false,
    isHiddenGem: true,
  },

  // JAIPUR
  {
    id: 'j1',
    name: 'Hawa Mahal',
    city: 'Jaipur',
    category: 'Historic',
    description: 'The Palace of Breeze. A stunning pink sandstone structure with 953 small windows designed for royal ladies to observe life below.',
    imageUrl: 'https://picsum.photos/seed/hawa/600/400',
    crowdLevel: 'High',
    authenticityScore: 70,
    rating: 4.7,
    reviews: 120000,
    lat: 26.9239,
    lng: 75.8267,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'j2',
    name: 'Panna Meena ka Kund',
    city: 'Jaipur',
    category: 'Historic',
    description: 'An ancient stepwell with geometric staircases. An architectural masterpiece that is surprisingly quiet even on busy weekends.',
    imageUrl: 'https://picsum.photos/seed/panna/600/400',
    crowdLevel: 'Low',
    authenticityScore: 91,
    rating: 4.6,
    reviews: 3200,
    lat: 26.9882,
    lng: 75.8540,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'j3',
    name: 'Galta Ji (Monkey Temple)',
    city: 'Jaipur',
    category: 'Historic',
    description: 'A pre-historic Hindu pilgrimage site tucked into a mountain pass. Features several sacred water tanks (kunds) and stunning architecture.',
    imageUrl: 'https://picsum.photos/seed/galta/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 95,
    rating: 4.5,
    reviews: 5800,
    lat: 26.9168,
    lng: 75.8596,
    isTouristFavorite: false,
    isHiddenGem: true,
  },

  // MUNNAR
  {
    id: 'mu1',
    name: 'Eravikulam National Park',
    city: 'Munnar',
    category: 'Nature',
    description: 'Home to the endangered Nilgiri Tahr. Offers sweeping views of misty tea estates and rolling green hills.',
    imageUrl: 'https://picsum.photos/seed/eravi/600/400',
    crowdLevel: 'High',
    authenticityScore: 82,
    rating: 4.6,
    reviews: 28000,
    lat: 10.1500,
    lng: 77.0600,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'mu2',
    name: 'Lakshmi Hills Trek',
    city: 'Munnar',
    category: 'Nature',
    description: 'A moderate trek through seven hills offering panoramic views of Idukki dam and Anamudi peak. Free from commercial crowds.',
    imageUrl: 'https://picsum.photos/seed/lakshmi/600/400',
    crowdLevel: 'Low',
    authenticityScore: 98,
    rating: 4.9,
    reviews: 120,
    lat: 10.0800,
    lng: 77.0400,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: 'mu3',
    name: 'Kolukkumalai Tea Estate',
    city: 'Munnar',
    category: 'Nature',
    description: 'The highest tea plantation in the world. Accessible only by jeep, it offers a sunrise that feels like you\'re above the clouds.',
    imageUrl: 'https://picsum.photos/seed/kolukkumalai/600/400',
    crowdLevel: 'Low',
    authenticityScore: 100,
    rating: 5.0,
    reviews: 800,
    lat: 10.0300,
    lng: 77.1900,
    isTouristFavorite: false,
    isHiddenGem: true,
  },

  // BANGALORE
  {
    id: 'b1',
    name: 'Cubbon Park',
    city: 'Bangalore',
    category: 'Park',
    description: 'The "Lung" of the city. A massive bamboo-filled park that becomes a walking paradise on Sunday mornings when traffic is banned.',
    imageUrl: 'https://picsum.photos/seed/cubbon/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 85,
    rating: 4.5,
    reviews: 42000,
    lat: 12.9750,
    lng: 77.5950,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'b2',
    name: 'Blossom Book House',
    city: 'Bangalore',
    category: 'Cafe',
    description: 'Not a cafe, but the soul of Church Street. A labyrinth of stacks where you can find almost any book ever printed in India.',
    imageUrl: 'https://picsum.photos/seed/blossom/600/400',
    crowdLevel: 'High',
    authenticityScore: 98,
    rating: 4.8,
    reviews: 15000,
    lat: 12.9752,
    lng: 77.6062,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: 'b3',
    name: 'VV Puram Food Street',
    city: 'Bangalore',
    category: 'Cafe',
    description: 'A narrow street that comes alive at 7 PM. Serving authentic South Indian street food, from Benne Masala Dosa to Honey Cake.',
    imageUrl: 'https://picsum.photos/seed/vvpuram/600/400',
    crowdLevel: 'High',
    authenticityScore: 100,
    rating: 4.7,
    reviews: 8900,
    lat: 12.9510,
    lng: 77.5770,
    isTouristFavorite: false,
    isHiddenGem: true,
  }
];
