export type CrowdLevel = 'Low' | 'Medium' | 'High';

export interface Place {
  id: string;
  name: string;
  city: string;
  category: 'Cafe' | 'Park' | 'Historic' | 'Beach' | 'Nature';
  description: string;
  imageUrl: string;
  crowdLevel: CrowdLevel;
  authenticityScore: number;
  rating: number;
  reviews: number;
  lat: number;
  lng: number;
  isTouristFavorite: boolean;
  isHiddenGem: boolean;
}

export const MOCK_PLACES: Place[] = [
  {
    id: '1',
    name: 'Indian Coffee House',
    city: 'Kolkata',
    category: 'Cafe',
    description: 'Iconic intellectual hub with high ceilings and white-uniformed waiters. Steeped in history and nostalgia.',
    imageUrl: 'https://picsum.photos/seed/kol-cafe/600/400',
    crowdLevel: 'High',
    authenticityScore: 85,
    rating: 4.5,
    reviews: 12500,
    lat: 22.5726,
    lng: 88.3639,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: '2',
    name: 'Sienna Store & Cafe',
    city: 'Kolkata',
    category: 'Cafe',
    description: 'A quiet, artistic sanctuary tucked away in Hindusthan Park. Features local pottery and organic food.',
    imageUrl: 'https://picsum.photos/seed/kol-hidden/600/400',
    crowdLevel: 'Low',
    authenticityScore: 95,
    rating: 4.8,
    reviews: 450,
    lat: 22.5186,
    lng: 88.3615,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: '3',
    name: 'Lodhi Garden',
    city: 'Delhi',
    category: 'Park',
    description: 'Vast city park containing architectural works of the 15th century. A favorite for morning walks and picnics.',
    imageUrl: 'https://picsum.photos/seed/del-park/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 78,
    rating: 4.6,
    reviews: 25000,
    lat: 28.5933,
    lng: 77.2189,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: '4',
    name: 'Sanjay Van',
    city: 'Delhi',
    category: 'Park',
    description: 'A sprawling city forest, peaceful and largely undisturbed. Perfect for spotting local birds and ancient ruins in silence.',
    imageUrl: 'https://picsum.photos/seed/del-forest/600/400',
    crowdLevel: 'Low',
    authenticityScore: 92,
    rating: 4.4,
    reviews: 320,
    lat: 28.5342,
    lng: 77.1706,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: '5',
    name: 'Marine Drive',
    city: 'Mumbai',
    category: 'Beach',
    description: 'The iconic "Queen\'s Necklace". A bustling promenade with stunning sunset views over the Arabian Sea.',
    imageUrl: 'https://picsum.photos/seed/mum-beach/600/400',
    crowdLevel: 'High',
    authenticityScore: 65,
    rating: 4.7,
    reviews: 85000,
    lat: 18.9431,
    lng: 72.8230,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: '6',
    name: 'Banganga Tank',
    city: 'Mumbai',
    category: 'Historic',
    description: 'An ancient water tank and holy temple complex. A remarkably calm spiritual pocket amidst Mumbai\'s chaos.',
    imageUrl: 'https://picsum.photos/seed/mum-tank/600/400',
    crowdLevel: 'Low',
    authenticityScore: 98,
    rating: 4.5,
    reviews: 1200,
    lat: 18.9454,
    lng: 72.7932,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: '7',
    name: 'Amer Fort',
    city: 'Jaipur',
    category: 'Historic',
    description: 'Majestic hill fort known for its artistic Hindu style elements. A must-visit landmark of Rajasthan.',
    imageUrl: 'https://picsum.photos/seed/jai-fort/600/400',
    crowdLevel: 'High',
    authenticityScore: 70,
    rating: 4.8,
    reviews: 62000,
    lat: 26.9855,
    lng: 75.8513,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: '8',
    name: 'Panna Meena ka Kund',
    city: 'Jaipur',
    category: 'Historic',
    description: 'Beautiful 16th-century stepwell. Famous for its geometric staircases, often overlooked by fort visitors.',
    imageUrl: 'https://picsum.photos/seed/jai-stepwell/600/400',
    crowdLevel: 'Low',
    authenticityScore: 88,
    rating: 4.6,
    reviews: 2100,
    lat: 26.9882,
    lng: 75.8540,
    isTouristFavorite: false,
    isHiddenGem: true,
  },
  {
    id: '9',
    name: 'Cubbon Park',
    city: 'Bangalore',
    category: 'Nature',
    description: 'The green heart of Bangalore. Massive bamboo groves and Victorian-era buildings throughout the park.',
    imageUrl: 'https://picsum.photos/seed/blr-park/600/400',
    crowdLevel: 'Medium',
    authenticityScore: 75,
    rating: 4.5,
    reviews: 18000,
    lat: 12.9750,
    lng: 77.5925,
    isTouristFavorite: true,
    isHiddenGem: false,
  },
  {
    id: '10',
    name: 'Turahalli Forest',
    city: 'Bangalore',
    category: 'Nature',
    description: 'A rocky hillock and dry deciduous forest. A favorite for local climbers and those seeking solitude.',
    imageUrl: 'https://picsum.photos/seed/blr-rock/600/400',
    crowdLevel: 'Low',
    authenticityScore: 94,
    rating: 4.3,
    reviews: 580,
    lat: 12.8752,
    lng: 77.5255,
    isTouristFavorite: false,
    isHiddenGem: true,
  }
];
